# Generated by Django 5.0.6 on 2024-06-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_orders_orders_product_user_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
    ]
