# Generated by Django 5.0.6 on 2024-07-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
    ]
