# Generated by Django 5.0.6 on 2024-07-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="product",
            field=models.ManyToManyField(
                related_name="ingredients", to="accounts.product"
            ),
        ),
    ]
