# Generated by Django 5.0.6 on 2024-07-02 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_ingredient_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="purchased",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
