# Generated by Django 5.0.6 on 2024-07-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_cartitem_quantity_productingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_ingredients",
                to="accounts.storage",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.ManyToManyField(
                through="accounts.ProductIngredient", to="accounts.storage"
            ),
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
