# Generated by Django 5.0.6 on 2024-07-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_productingredient_ingredient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="unit",
            field=models.CharField(default="کیلوگرم", max_length=50),
            preserve_default=False,
        ),
    ]
