# Generated by Django 5.0.6 on 2024-07-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_orders_product_quantity_alter_product_image'),
        ('accounts', '0017_alter_product_price'),
    ]

    operations = [
    ]
